# %%%%%%%%%%%%%%%%%%%%%%%%
# %%% FST CALCULATIONS %%%
# %%%%%%%%%%%%%%%%%%%%%%%%

# This script calculates Fst values for samples within the Q. tardifolia Texas red oak dataset. 
# It does this using the dartR function gl.fst.pop, which generates a matrix of distances between populations 
# and a matrix of p values. The function takes a genlight object as the main argument; this genlight object is 
# built from a genind object, which was generated using the Stacks populations module. 

# The following species are used as "populations", for the purpose of this calculation: gravesii, hypoleucoides,
# tardifolia and other known hybrids, and emoryi.

library(dartR)

# Specify the filepath to the Stacks populations directory for the Clust 3 FstCalcs dataset
FstCalcs_Dir <- 
  '/RAID1/QUTA_TX_RedOaks/Genotyping/SNP_Calling/Output/All_seReadsOnly/FstCalcs/'
FstCalcs_popmap <- 
  '/RAID1/QUTA_TX_RedOaks/Genotyping/SNP_Calling/Popmaps/QUTA_All_FstCalcs_popmap'
imageOutput_Dir <- 
  '/home/akoontz/Documents/QUTA_TxRedOaks/Documentation/Images/ManuscriptDraft_IJPS/revisedSubmission/'
setwd(FstCalcs_Dir)

# Function for plotting Fst values using a heatmap, given a matrix of values (and a title)
# The lower half of the fst_mat argument needs to have NA values, as does the diagonal 
Fst_plot <- function(fst_mat, title="Fst Values"){
  # Use image to plot a heatmap. First two arguments specify the boundaries of the heatmap; z provides actual values
  # z is transposed in order to plot numeral values later on
  image(x=1:ncol(fst_mat), y=1:nrow(fst_mat), z=fst_mat, axes=FALSE, xlab="", ylab="", 
        main=title)
  # Add boundary lines
  grid(nx=ncol(fst_mat), ny=nrow(fst_mat), col="black", lty=1)
  # Include sample names, to understand the context of genetic distances
  axis(1, 2:ncol(fst_mat), colnames(fst_mat)[2:4], cex.axis=1.2, tick=FALSE)
  text(1, c(1:nrow(fst_mat)), labels=rownames(fst_mat), cex=1.2)
  # Go through matrix, and plot values on each cell
  for(x in 1:ncol(fst_mat)){
    for(y in 2:nrow(fst_mat)){
      if(is.na(fst_mat[y,x])){
        # If value is empty (NA), add two hypens (instead of no value at all)
        text(y, x, "--", cex=1.5)
      } else {
        text(y, x, round(fst_mat[y,x], 5), cex=1.5)
      }
    }
  }
}

# Read in the genind file generated by the Stacks populations module
QUTA_All_FstCalc_genind <- read.genepop("QUTA_All_FstCalcs.gen")
pop(QUTA_All_FstCalc_genind) # Pop designations are incorrect, so this needs to be fixed
# Assign correect populations according to Stacks popmap file, and then check
pop(QUTA_All_FstCalc_genind) <- read.table(FstCalcs_popmap)[,2]
pop(QUTA_All_FstCalc_genind)
# Convert genind to genlight object
QUTA_All_FstCalc_genlight <- gi2gl(QUTA_All_FstCalc_genind)

# Calculate Fst values, specifying 2,000 bootstraps and 24 processing clusters
QUTA_All_FstCalc_FstMat <- gl.fst.pop(QUTA_All_FstCalc_genlight, nboots = 2000, nclusters = 24)

# PLOTTING
par(mar = c(2,1,4,1) + 0.1, oma = c(0,0.2,1.2,0), mgp = c(1,1,0)) # Specify unique plotting window
tiff(file = paste0(imageOutput_Dir, "FigS10_FstMat.tiff"), width = 1200, height = 795) # Save image to tiff
# Call customized plotting function
Fst_plot(QUTA_All_FstCalc_FstMat$Fsts, title='')
# Add title and subtitle
title(main='Fst Values: Dominant Taxa', line = 3)
mtext('7,317 loci; 2,000 bootstraps; p < 0.0005', line = 1.5, cex = 1.3)
dev.off() # Close plotting window
