#!/bin/bash

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %%% QUTA TEXAS RED OAKS: STACKS POPULATIONS CALL %%%
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# This script calls the Stacks populations command, which analyzes the SNP catalog generated by the ref_map.pl command, filters loci according to
# certain parameters, groups samples (as specified in the popmap file), and generates output files of different formats for downstream analyses.

# popmap files are stored in the SNP_Calling/Popmaps folder. For the purpose of this project, all samples are grouped into the same population ("wild").
# Filtering and file output parameters are explained below.

# %%% FILTERING PARAMETERS
# -R 98 : a locus must be present in at least 98% of individuals in order to be included in outputs
# --min-maf 0.01 : specifies a minor allele frequency of 1%, required to process a nucleotide site at a locus
# --write-single-snp : restrict data analysis to only the first SNP per locus. This reduces computational burden and allows for replicability across runs

# %%% OUTPUT PARAMETERS
# --hwe : calculate divergence from Hardy-Weinberg equilibrium for each locus
# --fstats : enable SNP and haplotype-base F statistics
# --vcf : output SNPs and haplotypes in Variant Call Format (VCF)
# --genepop : output results in GenePop format
# --structure : output results in Structure format
# --plink : output results in PLINK format
# --phylip-var-all : include all sequence as well as variable sites in the phylip output encoded using IUPAC notation

# %%% POPULATIONS CALL
populations -P ../originalOutput/ -O ./ -M ../../../Popmaps/QUTA_Clust2_popmap -t 30 -R 98 --min-maf 0.01 --hwe --write-single-snp --fstats --vcf --genepop --structure --plink --phylip-var-all
