# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares functions for taking the the summarized Q matrix values from a CLUMPP run 
# and building a corresponding STRUCTURE plot. Specifically, in terms of the outputs from CLUMPAK, 
# for a given K value, it reads in the CLUMPP output file ("CLUMPP.files/ClumppIndFile.output") 
# and will plot those values.

# Using several different wrapper functions, the script will analyze Q matrices to create STRUCTURE plots.
# It does this for both QUTA and QUBO, analyzing Subset Wild samples (that is, wild individuals that are
# analyzed in both MSAT and SNP studies, for each species)

# Processing note: CLUMPAK outputs locate results in folders named for each K value, with the format
# "K=2", "K=3", etc. Because the "=" symbol is difficult to deal with in BASH (similar to "/"),
# these folders have been manually renamed "K2", "K3", etc., for every CLUMPAK output folder.

library(RColorBrewer)
# Variable file path: directory to save images to
outputPlotDir <- 
  "/home/akoontz/Documents/QUTA_TxRedOaks/Documentation/Images/ManuscriptDraft_IJPS/"

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove sample name/population name columns as required 
read.CLUMPP <- function(clumpp.outputFile, sampleNames=NULL, popNames=NULL){
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  # If sample names exist, rename rows according to sample names
  if(hasArg(sampleNames)){
    rownames(Qmat) <- sampleNames
  }
  # If a vector of population names exists, add a column to the matrix which includes population identifiers
  if(hasArg(popNames)){
    Qmat <- cbind(popNames, Qmat)
    names(Qmat[,1]) <- "populations"
  }
  return(Qmat)
}

# Plotting function for single K value
plot.singleK <- function(kList, kColors, barWidth=1, title=NULL, popNamesPresent=FALSE, ...){
  # If population names are present (first column of matrix), remove these prior to plotting
  if(popNamesPresent){
    kList <- kList[,-1]
  } 
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], xlim=c(0,(nrow(kList)+20)), ylim=c(0,1.3), horiz=F, beside=F, 
              width=barWidth, col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset. Capture x positions (for possible use later)
      Xpos <- barplot(kList[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)),
                      width=barWidth, horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), 
       labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
  return(Xpos)
}

# Plotting function for single K value
plot.singleK_H <- function(kList, kColors, barWidth=1, title=NULL, popNamesPresent=FALSE, ...){
  # If population names are present (first column of matrix), remove these prior to plotting
  if(popNamesPresent){
    kList <- kList[,-1]
  } 
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], ylim=c(0,(nrow(kList)+20)), xlim=c(0,1.0), horiz=T, beside=F, 
              col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title, width=barWidth)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset. Capture x positions (for possible use later)
      Ypos <- barplot(kList[,i], offset=off.value, add=T, beside=F, ylim=c(0,(nrow(kList)+20)),
                      horiz=T, col=kColors[i], yaxt= "n", width=barWidth)
      off.value <- off.value + kList[,i]
    }
  }
  return(Ypos)
}

# Wrapper for plot_singleK, which calls that function after building filepath and reading in CLUMPP file
Plot.K <- function(clumppPath, K, Colors, barWidth=1, sampleNames, popNames, mainTitle=NULL, 
                   parFlag=FALSE, majorClust=TRUE, popNamesPresent=FALSE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Direct to the appropriate K folder, based on K argument
  Kfolder <- paste0("K", as.character(K),"/")
  # Read in the Q matrices in the ClumppIndFile.output file within the specified CLUMPP directory
  Kclumpp <- read.CLUMPP(paste0(clumppPath, Kfolder, clumppFolder, "ClumppIndFile.output"), 
                         sampleNames = sampleNames, popNames = popNames)
  # Plot K value
  Xpos <- plot.singleK(kList = Kclumpp, kValues = K, kColors = Colors, barWidth=barWidth, title=mainTitle, 
                       parFlag=parFlag, popNamesPresent = popNamesPresent)
  return(Xpos)
}

# Wrapper for plot_singleK, which calls that function after building filepath and reading in CLUMPP file
Plot.K_H <- function(clumppPath, K, Colors, barWidth=1, sampleNames, popNames, mainTitle=NULL, 
                   parFlag=FALSE, majorClust=TRUE, popNamesPresent=FALSE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Direct to the appropriate K folder, based on K argument
  Kfolder <- paste0("K", as.character(K),"/")
  # Read in the Q matrices in the ClumppIndFile.output file within the specified CLUMPP directory
  Kclumpp <- read.CLUMPP(paste0(clumppPath, Kfolder, clumppFolder, "ClumppIndFile.output"), 
                         sampleNames = sampleNames, popNames = popNames)
  # Plot K value, horizontally
  Ypos <- plot.singleK_H(kList = Kclumpp, kValues = K, kColors = Colors, barWidth=barWidth, 
                         title=mainTitle, parFlag=parFlag, popNamesPresent = popNamesPresent)
  return(Ypos)
}

# Plotting function for multiple K values
plot.multipleK <- function(kList, kValues, kColors, tickMarks, parFlag=TRUE, 
                           popNamesPresent=FALSE, titleFlag=TRUE, ...){
  # Determine the number of individuals by counting rows of the kList object
  nInds <- nrow(kList[[1]])
  # If parFlag argument is TRUE, specify graphing parameter values; otherwise, default (global) par values are utilized
  # parFlag variable allows for function to be used in different contexts (showing one marker, or all 3 markers)
  if(parFlag==TRUE){
    # Set graphing parameters to allow for multiple rows (for each K value).
    par(mfrow = c(length(kList),1), mar = c(1.2,1,1.5,0.75) + 0.1, oma = c(0.5,0,2,0), mgp = c(2,1,0))
  } 
  # Loop through list of Q matrices
  for(i in 1:length(kList)){
    # If population names are present (first column of matrix), remove these prior to plotting
    if(popNamesPresent){
      kList[[i]] <- kList[[i]][,-1]
    }
    # Update graphing parameters to allow for extra space at the bottom of the graph, for lines/popNames
    if(parFlag==TRUE){
      if(i == length(kList)){
        # par(mar = c(4,1,1,0.75) + 0.1)
        par(mar = c(5.5,1,1,0.75) + 0.1)
      }
    }
    # Main plot call, and title call
    Xpos <- barplot(t(kList[[i]]), beside= F, col=kColors, border = 1, space = 0.05, 
                    xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
    # For all but the last plot call, show tick marks (if specified)
    if(!is.null(tickMarks)){
      axis(1, at=tickMarks, labels = FALSE, lwd.ticks = 2.8, tck=-0.05)
      axis(1, at=tickMarks, labels = FALSE, lwd.ticks = 2.8, tck=1.05)
    }
  }
  return(Xpos)
}

# Wrapper for plot_multipleK, which just calls that function after reading in the CLUMPP files
Plot.AllK <- function(clumppPath, Ks, Colors, sampleNames, popNames, 
                      parFlag=TRUE, tickMarks=NULL, popNamesPresent=FALSE, majorClust=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Declare a list to be populated with filepaths to relevant CLUMPP files
  clumppList <- list()
  
  # For each K value, read in the corresponding CLUMPP files
  for(i in 1:length(Ks)){
    # Construct appropriate filepath and read in CLUMPP file
    Kfilepath <- paste0(clumppPath, "K", Ks[[i]], clumppFolder, "ClumppIndFile.output")
    Kclumpp <- read.CLUMPP(Kfilepath, sampleNames = sampleNames, popNames = popNames)
    # Add present CLUMPP file to list. Index is reduced by 1 because K values begin at K=2
    clumppList[[i]] <- Kclumpp
  }
  # Plot specified K values
  Xpos <- plot.multipleK(kList = clumppList, kValues = Ks, kColors = Colors, tickMarks=tickMarks, 
                         parFlag=parFlag, popNamesPresent = popNamesPresent)
  return(Xpos)
}

# %%%% VARIABLES %%%% ----
# Colors for different clusters. Rearranged to (partially) matche Clust2 patterns
QUTA_colors <- brewer.pal(12, "Paired")
QUTA_colors <- QUTA_colors[c(2,1,3:12)]
# Variable file path: directory containing all CLUMPP outputs to read in
QUTA_clust3_clumppDir <- 
  "/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Output/CLUMPAK/Output/mainPipeline/"
# Variable file path: directory to save images to
QUTA_imageOutDir <- '/home/akoontz/Documents/QUTA_TxRedOaks/Documentation/Images/MS_2025-10-26/'
# Read in text file of sample names
QUTA_clust3_sampleNames <- 
  as.list(read.table("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Clust3_sampleNames.txt", 
                     stringsAsFactors = FALSE))
# Reformat sample names as a vector
QUTA_clust3_sampleNames <- unname(unlist(QUTA_clust3_sampleNames))
# Remove prefixes ('SYST-MOR-000','OAK-M**-000' ), to make names discernible
QUTA_clust3_sampleNames <- sub('SYST-MOR-000','', QUTA_clust3_sampleNames)
QUTA_clust3_sampleNames <- sub('OAK-MOR-00','', QUTA_clust3_sampleNames)
QUTA_clust3_sampleNames <- sub('OAK-MOR-000','', QUTA_clust3_sampleNames)
QUTA_clust3_sampleNames <- sub('OAK-UMN-000','', QUTA_clust3_sampleNames)
QUTA_clust3_sampleNames <- sub('SH-Q','', QUTA_clust3_sampleNames)
# Group labels for clust3
clust3_labels <- c('gravesii','grav. x emoryi','emoryi','canbyi',
                   'hypo.','grav. x hypo.')

# %%%% PLOTTING %%%% ----
# %%%% ALL K VALUES ----
# Label and tick mark positions (Multiple K values)
clust3_labelPositions_multipleK <- c(9, 24, 40, 52, 64.5, 77)
clust3_tickMarks_multipleK <- c(0,15.8,30.4,47.2,56.8,72.6)
# Plot results from all K values
Xpos <- Plot.AllK(QUTA_clust3_clumppDir, Ks=2:7, QUTA_colors, sampleNames = QUTA_clust3_sampleNames, 
                  majorClust = TRUE, tickMarks = clust3_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=clust3_labelPositions_multipleK, y=-0.08, srt=35, adj=1, xpd=TRUE, labels=clust3_labels, cex=1.2)
# Add horizontal bar, indicating tardifolia individuals
axis(1, at=c(79,88.3), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0)

# %%%% SUBSET K VALUES ----
# Label and tick mark positions (Multiple K values)
clust3_labelPositions_multipleK <- c(9, 24, 40, 52, 64.5, 77)
clust3_tickMarks_multipleK <- c(0,15.8,30.4,47.2,56.8,72.6)
# Plot K values 2 through 4
Xpos <- Plot.AllK(QUTA_clust3_clumppDir, Ks=2:4, QUTA_colors, sampleNames = QUTA_clust3_sampleNames, 
                  majorClust = TRUE, tickMarks=clust3_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=clust3_labelPositions_multipleK, y=-0.06, srt=35, adj=1, xpd=TRUE, labels=clust3_labels, cex=1.2)
# Add horizontal bar, indicating tardifolia individuals
axis(1, at=c(79,88.3), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0)
# Plot K values 5 through 7
Xpos <- Plot.AllK(QUTA_clust3_clumppDir, Ks=5:7, QUTA_colors, sampleNames = QUTA_clust3_sampleNames, 
              majorClust = TRUE, tickMarks=clust3_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=clust3_labelPositions_multipleK, y=-0.06, srt=35, adj=1, xpd=TRUE, labels=clust3_labels, cex=1.2)
# Add horizontal bar, indicating tardifolia individuals
axis(1, at=c(79,88.3), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0)

# %%%% %%%% MANUSCRIPT DRAFT: SUBSET K VALUES ----
# Group labels for Clust3
clust3_labels <- c('gravesii','graciliformis','emoryi, robusta','canbyi, miq.',
                   'hypoleucoides', 'scytophylla','grav. x hypo.', 'tardifolia')
# Label and tick mark positions (Multiple K values)
clust3_labelPositions_multipleK <- c(9, 26, 39, 53, 64.2, 71, 78.4, 84.2)
clust3_tickMarks_multipleK <- c(0,15.8,30.4,46.2,56.8,66.2,72.6,78.8)

# PLOT K VALUES 2 THROUGH 4
# Save the image to a TIFF
tiff(file = paste0(outputPlotDir, "FigS5_Clust2-STR_K2-4.tiff"), width = 1200, height = 795)
# Call plot command
Xpos <- Plot.AllK(QUTA_clust3_clumppDir, Ks=2:4, QUTA_colors, sampleNames = QUTA_clust3_sampleNames, 
                  majorClust = TRUE, tickMarks=clust3_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=clust3_labelPositions_multipleK, y=1.03, srt=0, adj=1, xpd=TRUE, 
     labels=clust3_labels, cex=1.2, font=2)
# Add sample names below the graph
text(x=Xpos, y=-0.013, srt=87, adj=1, xpd=TRUE, labels=QUTA_clust3_sampleNames, cex=1.2)
# Close plotting window
dev.off()

# PLOT K VALUES 5 THROUGH 7
# Save the image to a TIFF
tiff(file = paste0(outputPlotDir, "FigS6_Clust2-STR_K5-7.tiff"), width = 1200, height = 795)
# Call plot command
Xpos <- Plot.AllK(QUTA_clust3_clumppDir, Ks=5:7, QUTA_colors, sampleNames = QUTA_clust3_sampleNames, 
                  majorClust = TRUE, tickMarks=clust3_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=clust3_labelPositions_multipleK, y=1.03, srt=0, adj=1, xpd=TRUE, 
     labels=clust3_labels, cex=1.2, font=2)
# Add sample names below the graph
text(x=Xpos, y=-0.013, srt=87, adj=1, xpd=TRUE, labels=QUTA_clust3_sampleNames, cex=1.2)
# Close plotting window
dev.off()

# %%%% K=4 VALUES ----
# Specify graphing parameters to plot single K value
dev.off()
par(mar = c(8,1.2,0.5,0.5) + 0.1, oma = c(0,0.2,0,0), mgp = c(1,1,0))
# Label and tick mark positions (K=4)
clust3_labelPositions_K4 <- c(11, 28, 46.3, 60.2, 75, 87.5)
clust3_tickMarks_K4 <- c(0,18,35,54,65,82.8)
# Plot K = 4 on its own, returning x positions of vertical bars
Xpos <- Plot.K(QUTA_clust3_clumppDir, 4, QUTA_colors, mainTitle = "",  majorClust=TRUE, 
               popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, showSampleNames = TRUE)
# Add title
title('QUTA_TxRedOaks: K=4', line = -1.3)
mtext('Single Reads Only; R98, 9,954 loci; Third STRUCTURE Run', line=-2.6)
# Plot tick marks (along bottom)
axis(1, at=clust3_tickMarks_K4, labels = FALSE, lwd.ticks = 3, tck=-0.05)
axis(1, at=clust3_tickMarks_K4, labels = FALSE, lwd.ticks = 3, tck=0.79)
# Add group labels
text(x=clust3_labelPositions_K4, y=-0.03, srt=35, adj=1, xpd=TRUE, labels=clust3_labels, cex=1.2)
# Add horizontal bar, indicating tardifolia individuals
axis(1, at=c(90.4,100.5), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0)

# %%%% K=4 VALUES, WITH SAMPLE NAMES ----
# Specify graphing parameters to plot single K value
par(mar = c(8,1,0.5,3) + 0.1, oma = c(0,0.2,0,0), mgp = c(1,1,0))
# Plot K = 4 on its own, returning x positions of vertical bars
Xpos <- Plot.K(QUTA_clust3_clumppDir, 4, QUTA_colors, mainTitle = "",  majorClust=TRUE, 
               popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, showSampleNames = TRUE)
# Add title
title('QUTA_TxRedOaks: K=4', line = -1.3)
mtext('Single Reads Only; R98, 9,954 loci; Third STRUCTURE Run', line=-2.6)
# Plot tick marks (along bottom)
axis(1, at=clust3_tickMarks_K4, labels = FALSE, lwd.ticks = 3, tck=-0.05)
axis(1, at=clust3_tickMarks_K4, labels = FALSE, lwd.ticks = 3, tck=0.79)
# Add sample names below the graph
text(x=Xpos, y=-0.007, srt=83, adj=1, xpd=TRUE, labels=QUTA_clust3_sampleNames, cex=0.8)

# %%%% K=4 VALUES, WITH SAMPLE NAMES, SUMMARY CLUSTERS ----
# Specify graphing parameters to plot single K value
par(mar = c(8,1,0.5,3) + 0.1, oma = c(0,0.2,0,0), mgp = c(1,1,0))
# Plot K = 4 on its own, returning x positions of vertical bars
Xpos <- Plot.K(QUTA_clust3_clumppDir, 4, QUTA_colors, mainTitle = "",  majorClust=FALSE, 
               popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, showSampleNames = TRUE)
# Add title
title('QUTA_TxRedOaks: K=4', line = -1.3)
mtext('Single Reads Only; R98, 9,954 loci; Third STRUCTURE Run', line=-2.6)
# Plot tick marks (along bottom)
axis(1, at=clust3_tickMarks_K4, labels = FALSE, lwd.ticks = 3, tck=-0.05)
axis(1, at=clust3_tickMarks_K4, labels = FALSE, lwd.ticks = 3, tck=0.79)
# Add sample names below the graph
text(x=Xpos, y=-0.007, srt=83, adj=1, xpd=TRUE, labels=QUTA_clust3_sampleNames, cex=0.8)

# %%%% K=4 VALUES, WITH SAMPLE NAMES, HORIZONTALLY ----
# Tick mark positions for K=4, horizontal
clust3_tickMarks_K4_H <- c(0,36,70.1,108,130,166)
# Read in text file of sample names and dets
QUTA_clust3_sampleNamesAndDets <- 
  as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Clust3_sampleNamesAndDets.csv", 
                     stringsAsFactors = FALSE, header = FALSE))
# Reformat sample names as a vector
QUTA_clust3_sampleNamesAndDets <- unname(unlist(QUTA_clust3_sampleNamesAndDets))
# Replace commas with semicolons
QUTA_clust3_sampleNamesAndDets <- sub(',',' ; ', QUTA_clust3_sampleNamesAndDets)
# Specify graphing parameters to plot single K value horizontally
dev.off()
par(mar = c(2,0.2,19.5,12) + 0.1, oma = c(0,0.2,1.2,0.5), mgp = c(1,1,0))
# Call png command, to save plots to disk
png(file = paste0(QUTA_imageOutDir, "Fig2_STR_K4.png"), width = 795, height = 1200)
# Plot K = 4 on its own, horizontally
Ypos <- Plot.K_H(QUTA_clust3_clumppDir, 4, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2)
# Add title
title('Q. tardifolia and Texas Red Oaks: K=4', line = 18.5)
mtext('R98, 9,954 loci', line=17.2)
# title('Q. tardifolia and Texas Red Oaks: K=4', line = 14.3)
# mtext('R98, 9,954 loci', line=13.3)
# Plot tick marks (horizontally)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 3, tck=-0.01, xpd=TRUE)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 3, tck=1.005, xpd=TRUE)
# Add sample names along the graph (on the right)
text(x=1.005, y=Ypos, srt=0, adj=0, xpd=TRUE, labels=QUTA_clust3_sampleNamesAndDets, cex=0.78)

# %%%% MANUSCRIPT DRAFT 3, FIGURE 2: K=4, HORIZONTAL, DET NAMES ----
# Tick mark positions for K=4, horizontal
clust3_tickMarks_K4_H <- c(0,40.6,80.9,119,145.4,168,186,203)
# Read in text file of sample names and dets
# QUTA_clust3_sampleNamesAndDets <- 
#   as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Clust3_sampleNamesAndDets.csv", 
#                     stringsAsFactors = FALSE, header = FALSE))
QUTA_clust3_sampleDets <- 
  as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Clust3_sampleDets.csv", 
                    stringsAsFactors = FALSE, header = TRUE))
# Reformat sample names as a vector
QUTA_clust3_sampleDets <- unname(unlist(QUTA_clust3_sampleDets))
# # Replace commas with semicolons
# QUTA_clust3_sampleDets <- QUTA_clust3_sampleDets[-1]
# Specify graphing parameters to plot single K value horizontally
par(mar = c(2,0.2,16.75,12) + 0.1, oma = c(0,0.2,1.2,0.5), mgp = c(1,1,0))
# Plot K = 4 on its own, horizontally
Ypos <- Plot.K_H(QUTA_clust3_clumppDir, 4, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2.25)
# Add title
title('Q. tardifolia and Texas Red Oaks: K=4', line = 16.1)
mtext('R98, 9,954 loci', line=15.1)
# Plot tick marks (horizontally)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 3, tck=-0.01, xpd=TRUE)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 3, tck=1.005, xpd=TRUE)
# Add sample names along the graph (on the right)
text(x=1.005, y=Ypos, srt=0, adj=0, xpd=TRUE, labels=QUTA_clust3_sampleDets, cex=0.7)
# Save image to PNG: height 1200, width 660

# %%%% MANUSCRIPT DRAFT 1, FIGURE 2: K=4, HORIZONTAL, SAMPLE NAMES ----
# Tick mark positions for K=4, horizontal
clust3_tickMarks_K4_H <- c(0,40.6,80.9,119,145.4,168,186,203)
# Read in text file of sample names and dets
QUTA_clust3_sampleNamesAndDets <- 
  as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Clust3_NamesAndDets.csv", 
                    stringsAsFactors = FALSE, header = TRUE))
# Reformat sample names as a vector
QUTA_clust3_sampleNamesAndDets <- unname(unlist(QUTA_clust3_sampleNamesAndDets))
# Replace commas with semicolons
QUTA_clust3_sampleNamesAndDets <- sub(',',' ; ', QUTA_clust3_sampleNamesAndDets)
# Specify graphing parameters to plot single K value horizontally
par(mar = c(2,0.2,16.75,12) + 0.1, oma = c(0,0.2,1.2,0.5), mgp = c(1,1,0))
# Plot K = 4 on its own, horizontally
Ypos <- Plot.K_H(QUTA_clust3_clumppDir, 4, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2.25)
# Add title
title('Q. tardifolia and Texas Red Oaks: K=4', line = 16.1)
mtext('R98, 9,954 loci', line=15.1)
# Plot tick marks (horizontally)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 3, tck=-0.01, xpd=TRUE)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 3, tck=1.005, xpd=TRUE)
# Add sample names along the graph (on the right)
text(x=1.005, y=Ypos, srt=0, adj=0, xpd=TRUE, labels=QUTA_clust3_sampleNamesAndDets, cex=0.7)
# Save image to PNG: height 1200, width 660

# %%%% K=4 VALUES, SUMMARY CLUSTERS, HORIZONTALLY: MANUSCRIPT DRAFT 3 ----
# Read in text file of sample names and dets
QUTA_clust3_sampleNamesAndDets <- 
  as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_seOnly/Clust3_NamesAndDets.csv", 
                    stringsAsFactors = FALSE, header = TRUE))
# Reformat sample names as a vector
QUTA_clust3_sampleNamesAndDets <- unname(unlist(QUTA_clust3_sampleNamesAndDets))
# Replace commas with semicolons
QUTA_clust3_sampleNamesAndDets <- sub(',',' ; ', QUTA_clust3_sampleNamesAndDets)
# # Tick mark positions for K=4, horizontal
# clust3_tickMarks_K4_H <- c(0,36,70.1,108,130,166)
# Specify unique vector of colors
# QUTA_colors <- c("#FFB000", "#785EF0", "#DC267F", "#FE6100")
# Specify general names and locations, for groups in graph
QUTA_clust3_clusterNames <- c('gravesii', 'graciliformis','emoryi','canbyi','hypoleucoides','tardifolia')
QUTA_clust3_clusterPos <- c(20,51,87,117,147,182)
# Reformat sample names as a vector
QUTA_clust3_sampleNamesAndDets <- unname(unlist(QUTA_clust3_sampleNamesAndDets))
# Replace commas with semicolons
QUTA_clust3_sampleNamesAndDets <- sub(',',' ; ', QUTA_clust3_sampleNamesAndDets)
# Specify graphing parameters to plot single K value horizontally
par(mar = c(2,0.2,16.7,7) + 0.1, oma = c(0,0.2,1.2,0), mgp = c(1,1,0))
# Plot K = 4 on its own, horizontally (PNG figure width: 1500)
Ypos <- Plot.K_H(QUTA_clust3_clumppDir, 4, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_clust3_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2)
# Add title
title('Q. tardifolia and Texas Red Oaks: K=4', line = 16)
mtext('9,954 loci, R98', line=14.6)

# Add horizontal bar, indicating tardifolia individuals
axis(4, at=c(0,37.5), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # gravesii
axis(4, at=c(40.0,49.1), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # gravesii x emoryi
axis(4, at=c(52.0,63.2), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # gracilliformis
axis(4, at=c(67.0,75.1), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # emoryi
axis(4, at=c(85.2,96.7), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # canbbyi
axis(4, at=c(99.1,100.1), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # miquihuaensis
axis(4, at=c(100.6,105.3), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # hypoleucoides
axis(4, at=c(107.2,112.4), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # scytophylla
axis(4, at=c(112.9,116.5), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # gravesii x hypoleucoides
axis(4, at=c(190.1,223.2), labels = FALSE, line=0.4, lwd = 2, lwd.ticks = 0) # tardifolia

# Plot tick marks (horizontally)
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 4, tck=-0.05, xpd=TRUE, col='black')
axis(4, at=clust3_tickMarks_K4_H, labels = FALSE, lwd.ticks = 4, tck=1.005, xpd=TRUE, col='black')
# Add summary cluster names along the right
text(x=1.005, y=QUTA_clust3_clusterPos, srt=0, adj=0, xpd=TRUE, 
     labels=QUTA_clust3_clusterNames, cex=1.25)

# %%%% SCY-HYPO-CAN-TAR DATASET %%%% ----
# %%%% VARIABLES ----
# Colors for different clusters
QUTA_colors <- brewer.pal(12, "Paired")
# Read in text file of sample names
QUTA_ScyHypoCanTar_sampleNames <- 
  as.list(read.table("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/ScyHypoCanTar/pop_R98/ScyHypoCanTar_sampleNames.txt", 
                     stringsAsFactors = FALSE))
# Reformat sample names as a vector
QUTA_ScyHypoCanTar_sampleNames <- unname(unlist(QUTA_ScyHypoCanTar_sampleNames))
# Remove prefixes ('SYST-MOR-000','OAK-M**-000' ), to make names discernible
QUTA_ScyHypoCanTar_sampleNames <- sub('SYST-MOR-000','', QUTA_ScyHypoCanTar_sampleNames)
QUTA_ScyHypoCanTar_sampleNames <- sub('OAK-MOR-00','', QUTA_ScyHypoCanTar_sampleNames)
QUTA_ScyHypoCanTar_sampleNames <- sub('OAK-MOR-000','', QUTA_ScyHypoCanTar_sampleNames)
QUTA_ScyHypoCanTar_sampleNames <- sub('OAK-UMN-000','', QUTA_ScyHypoCanTar_sampleNames)
# Group labels for ScyHypoCanTar
ScyHypoCanTar_labels <- c('canbyi','miqui.','hypo.','scytophylla','grav x hypo','tardifolia')
# Label and tick mark positions (Multiple K values)
ScyHypoCanTar_labelPositions_multipleK <- c(4,9,16.5,24,30,37)
ScyHypoCanTar_tickMarks_multipleK <- c(0,6.3,10.5,20,26.3,32.6,42)

# %%%% PLOTTING %%%% ----
# %%%% R98 ----
# Variable file path: directory containing all CLUMPP outputs to read in
QUTA_ScyHypoCanTar_R98_clumppDir <- 
  "/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/ScyHypoCanTar/pop_R98/Output/CLUMPAK/Output/mainPipeline/"
# %%%% K VALUES 2--6 ----
Xpos <- 
  Plot.AllK(QUTA_ScyHypoCanTar_R98_clumppDir, Ks=2:6, QUTA_colors, sampleNames = QUTA_ScyHypoCanTar_sampleNames, 
            majorClust = TRUE, tickMarks = ScyHypoCanTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=ScyHypoCanTar_labelPositions_multipleK, y=-0.08, srt=35, adj=1, xpd=TRUE, labels=ScyHypoCanTar_labels, cex=1.2)

# %%%% R97_WL10K ----
# Variable file path: directory containing all CLUMPP outputs to read in
QUTA_ScyHypoCanTar_R97WL10K_clumppDir <- 
  "/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/ScyHypoCanTar/pop_R97_WL10K/Output/CLUMPAK/Output/mainPipeline/"
# ALL K VALUES (2--8) ----
Xpos <- 
  Plot.AllK(QUTA_ScyHypoCanTar_R97WL10K_clumppDir, Ks=2:8, QUTA_colors, sampleNames = QUTA_ScyHypoCanTar_sampleNames, 
            majorClust = TRUE, tickMarks = ScyHypoCanTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=ScyHypoCanTar_labelPositions_multipleK, y=-0.08, srt=35, adj=1, xpd=TRUE, labels=ScyHypoCanTar_labels, cex=1.2)
# K VALUES 2--5 ----
Xpos <- 
  Plot.AllK(QUTA_ScyHypoCanTar_R97WL10K_clumppDir, Ks=2:5, QUTA_colors, sampleNames = QUTA_ScyHypoCanTar_sampleNames, 
            majorClust = TRUE, tickMarks = ScyHypoCanTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=ScyHypoCanTar_labelPositions_multipleK, y=-0.08, srt=35, adj=1, xpd=TRUE, labels=ScyHypoCanTar_labels, cex=1.2)
# K VALUES 6--8 ----
Xpos <- 
  Plot.AllK(QUTA_ScyHypoCanTar_R97WL10K_clumppDir, Ks=6:8, QUTA_colors, sampleNames = QUTA_ScyHypoCanTar_sampleNames, 
            majorClust = TRUE, tickMarks = ScyHypoCanTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=ScyHypoCanTar_labelPositions_multipleK, y=-0.08, srt=35, adj=1, xpd=TRUE, labels=ScyHypoCanTar_labels, cex=1.2)
# HORIZONTAL STRUCTURE PLOTS ----
# Tick mark positions for K=6, horizontal
ScyHypoCanTar_tickMarks_H <- c(0,15,24,45.7,60.4,74.7)
# Read in text file of sample names and dets
QUTA_ScyHypoCanTar_sampleNamesAndDets <- 
  as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/ScyHypoCanTar/pop_R97_WL10K/ScyHypoCanTar_sampleNamesAndDets.csv", 
                    stringsAsFactors = FALSE, header = TRUE))
# Reformat sample names as a vector
QUTA_ScyHypoCanTar_sampleNamesAndDets <- unlist(unname(QUTA_ScyHypoCanTar_sampleNamesAndDets))
# Put asterisks next to the sample names with higher levels of missing data (>10%)
QUTA_ScyHypoCanTar_sampleNamesAndDets[[8]] <- "6235*, hypoxantha"
QUTA_ScyHypoCanTar_sampleNamesAndDets[[39]] <- "6654*, hypoxantha x gravesii"
QUTA_ScyHypoCanTar_sampleNamesAndDets[[40]] <- "6656*, tardifolia"
# Specify graphing parameters to plot single K value horizontally
dev.off()
par(mar = c(2.1,0.6,12.6,11) + 0.1, oma = c(0,0.2,1.2,0), mgp = c(1,1,0))
# K=3 ----
# Plot K = 6 on its own, horizontally
Ypos <- Plot.K_H(QUTA_ScyHypoCanTar_R97WL10K_clumppDir, 3, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_ScyHypoCanTar_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2)
# Add title
title('QUTA_TxRedOaks: ScyHypoCanTar Dataset: K=3', line = 11.9)
mtext('Single Reads Only; R97, 10,000 loci (Whitelist)', line=11)
# Plot tick marks (horizontally)
axis(4, at=ScyHypoCanTar_tickMarks_H, labels = FALSE, lwd.ticks = 2.5, tck=-0.03, xpd=TRUE)
axis(4, at=ScyHypoCanTar_tickMarks_H, labels = FALSE, lwd.ticks = 2.5, tck=1.005, xpd=TRUE)
# Add sample names along the graph (on the right)
text(x=1.005, y=Ypos, srt=0, adj=0, xpd=TRUE, labels=QUTA_ScyHypoCanTar_sampleNamesAndDets, cex=0.78)

# K=6 ----
# Plot K = 6 on its own, horizontally
Ypos <- Plot.K_H(QUTA_ScyHypoCanTar_R97WL10K_clumppDir, 6, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_ScyHypoCanTar_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2)
# Add title
title('QUTA_TxRedOaks: ScyHypoCanTar Dataset: K=6', line = 11.9)
mtext('Single Reads Only; R97, 10,000 loci (Whitelist)', line=11)
# Plot tick marks (horizontally)
axis(4, at=ScyHypoCanTar_tickMarks_H, labels = FALSE, lwd.ticks = 2.5, tck=-0.03, xpd=TRUE)
axis(4, at=ScyHypoCanTar_tickMarks_H, labels = FALSE, lwd.ticks = 2.5, tck=1.005, xpd=TRUE)
# Add sample names along the graph (on the right)
text(x=1.005, y=Ypos, srt=0, adj=0, xpd=TRUE, labels=QUTA_ScyHypoCanTar_sampleNamesAndDets, cex=0.78)

# %%%% GRAV-HYPO-TAR DATASET %%%% ----
# %%%% VARIABLES ----
# Colors for different clusters
QUTA_colors <- brewer.pal(12, "Paired")
# Read in text file of sample names
QUTA_GravHypoTar_sampleNames <- 
  as.list(read.table("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_GravHypoTar/QUTA_Clust3_GravHypoTar_sampleNames.txt", 
                     stringsAsFactors = FALSE))
# Reformat sample names as a vector
QUTA_GravHypoTar_sampleNames <- unname(unlist(QUTA_GravHypoTar_sampleNames))
# Remove prefixes ('SYST-MOR-000','OAK-M**-000' ), to make names discernible
QUTA_GravHypoTar_sampleNames <- sub('SYST-MOR-000','', QUTA_GravHypoTar_sampleNames)
QUTA_GravHypoTar_sampleNames <- sub('OAK-MOR-00','', QUTA_GravHypoTar_sampleNames)
QUTA_GravHypoTar_sampleNames <- sub('OAK-MOR-000','', QUTA_GravHypoTar_sampleNames)
QUTA_GravHypoTar_sampleNames <- sub('OAK-UMN-000','', QUTA_GravHypoTar_sampleNames)
# Group labels for GravHypoTar
GravHypoTar_labels <- c('gravesii','hypoleucoides','grav x hypo','tardifolia')
# Label and tick mark positions (Multiple K values)
GravHypoTar_labelPositions_multipleK <- c(7,23,34.6,42.4)
GravHypoTar_tickMarks_multipleK <- c(0,15.8,31.5,37.8)

# %%%% PLOTTING %%%% ----
# %%%% R98_WL10K ----
# Variable file path: directory containing all CLUMPP outputs to read in
QUTA_GravHypoTar_clumppDir <- 
  "/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_GravHypoTar/Output/CLUMPAK/Output/mainPipeline/"
# ALL K VALUES (2--7) ----
Xpos <- 
  Plot.AllK(QUTA_GravHypoTar_clumppDir, Ks=2:7, QUTA_colors, sampleNames = QUTA_GravHypoTar_sampleNames, 
            majorClust = TRUE, tickMarks = GravHypoTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=GravHypoTar_labelPositions_multipleK, y=-0.12, srt=35, adj=1, xpd=TRUE, labels=GravHypoTar_labels, cex=1.2)
# K VALUES 2--4 ----
Xpos <- 
  Plot.AllK(QUTA_GravHypoTar_clumppDir, Ks=2:4, QUTA_colors, sampleNames = QUTA_GravHypoTar_sampleNames, 
            majorClust = TRUE, tickMarks = GravHypoTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=GravHypoTar_labelPositions_multipleK, y=-0.12, srt=35, adj=1, xpd=TRUE, labels=GravHypoTar_labels, cex=1.2)
# K VALUES 5--7 ----
Xpos <- 
  Plot.AllK(QUTA_GravHypoTar_clumppDir, Ks=5:7, QUTA_colors, sampleNames = QUTA_GravHypoTar_sampleNames, 
            majorClust = TRUE, tickMarks = GravHypoTar_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=GravHypoTar_labelPositions_multipleK, y=-0.12, srt=35, adj=1, xpd=TRUE, labels=GravHypoTar_labels, cex=1.2)

# HORIZONTAL STRUCTURE PLOT ----
# Tick mark positions for K=6, horizontal
GravHypoTar_tickMarks_H <- c(0,35.9,72.5,86.5)
# Read in text file of sample names and dets
QUTA_GravHypoTar_sampleNamesAndDets <- 
  as.list(read.csv2("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust3_GravHypoTar/GravHypoTar_SampleList.csv", 
                    stringsAsFactors = FALSE, header = TRUE))
# Reformat sample names as a vector
QUTA_GravHypoTar_sampleNamesAndDets <- unlist(unname(QUTA_GravHypoTar_sampleNamesAndDets))
# Specify graphing parameters to plot single K value horizontally
dev.off()
par(mar = c(2.1,0.6,11.2,11) + 0.1, oma = c(0,0.2,1.2,0), mgp = c(1,1,0))
# K=2 ----
# Plot K = 6 on its own, horizontally
Ypos <- Plot.K_H(QUTA_GravHypoTar_clumppDir, K=2, QUTA_colors, majorClust=TRUE, 
                 popNamesPresent=FALSE, sampleNames = QUTA_GravHypoTar_sampleNames, 
                 showSampleNames = TRUE, hFlag=TRUE, barWidth = 2)
# Add title
title('QUTA_TxRedOaks: GravHypoTar Dataset: K=2', line = 10.4)
mtext('Single Reads Only; R98, 10,000 loci (Whitelist)', line=9.2)
# Plot tick marks (horizontally)
axis(4, at=GravHypoTar_tickMarks_H, labels = FALSE, lwd.ticks = 2.5, tck=-0.03, xpd=TRUE)
axis(4, at=GravHypoTar_tickMarks_H, labels = FALSE, lwd.ticks = 2.5, tck=1.005, xpd=TRUE)
# Add sample names along the graph (on the right)
text(x=1.005, y=Ypos, srt=0, adj=0, xpd=TRUE, labels=QUTA_GravHypoTar_sampleNamesAndDets, cex=0.78)
