# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares functions for taking the the summarized Q matrix values from a CLUMPP run 
# and building a corresponding STRUCTURE plot. Specifically, in terms of the outputs from CLUMPAK, 
# for a given K value, it reads in the CLUMPP output file ("CLUMPP.files/ClumppIndFile.output") 
# and will plot those values.

# Using several different wrapper functions, the script will analyze Q matrices to create STRUCTURE plots.
# It does this for both QUTA and QUBO, analyzing Subset Wild samples (that is, wild individuals that are
# analyzed in both MSAT and SNP studies, for each species)

# Processing note: CLUMPAK outputs locate results in folders named for each K value, with the format
# "K=2", "K=3", etc. Because the "=" symbol is difficult to deal with in BASH (similar to "/"),
# these folders have been manually renamed "K2", "K3", etc., for every CLUMPAK output folder.

library(RColorBrewer)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove sample name/population name columns as required 
read.CLUMPP <- function(clumpp.outputFile, sampleNames=NULL, popNames=NULL){
  # browser()
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  # If sample names exist, rename rows according to sample names
  if(hasArg(sampleNames)){
    rownames(Qmat) <- sampleNames
  }
  # If a vector of population names exists, add a column to the matrix which includes population identifiers
  if(hasArg(popNames)){
    Qmat <- cbind(popNames, Qmat)
    names(Qmat[,1]) <- "populations"
  }
  return(Qmat)
}

# Plotting function for single K value
plot.singleK <- function(kList, kColors, barWidth=1, title=NULL, popNamesPresent=FALSE, ...){
  # browser()
  # If population names are present (first column of matrix), remove these prior to plotting
  if(popNamesPresent){
    kList <- kList[,-1]
  } 
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], xlim=c(0,(nrow(kList)+20)), ylim=c(0,1.3), horiz=F, beside=F, 
              width=barWidth, col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset. Capture x positions (for possible use later)
      Xpos <- barplot(kList[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)),
                      width=barWidth, horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), 
       labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
  return(Xpos)
}

# Wrapper for plot_singleK, which calls that function after building filepath and reading in CLUMPP file
Plot.K <- function(clumppPath, K, Colors, barWidth=1, sampleNames, popNames, mainTitle=NULL, 
                   parFlag=FALSE, majorClust=TRUE, popNamesPresent=FALSE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Direct to the appropriate K folder, based on K argument
  Kfolder <- paste0("K", as.character(K),"/")
  # Read in the Q matrices in the ClumppIndFile.output file within the specified CLUMPP directory
  Kclumpp <- read.CLUMPP(paste0(clumppPath, Kfolder, clumppFolder, "ClumppIndFile.output"), 
                         sampleNames = sampleNames, popNames = popNames)
  # Plot K value
  Xpos <- plot.singleK(kList = Kclumpp, kValues = K, kColors = Colors, barWidth=barWidth, title=mainTitle, 
               parFlag=parFlag, popNamesPresent = popNamesPresent)
  return(Xpos)
}

# Plotting function for multiple K values
plot.multipleK <- function(kList, kValues, kColors, tickMarks, parFlag=TRUE, 
                           popNamesPresent=FALSE, titleFlag=TRUE, ...){
  # Determine the number of individuals by counting rows of the kList object
  nInds <- nrow(kList[[1]])
  # If parFlag argument is TRUE, specify graphing parameter values; otherwise, default (global) par values are utilized
  # parFlag variable allows for function to be used in different contexts (showing one marker, or all 3 markers)
  if(parFlag==TRUE){
    # Set graphing parameters to allow for multiple rows (for each K value).
    par(mfrow = c(length(kList),1), mar = c(1.2,1,1.5,0.75) + 0.1, oma = c(0.5,0,2,0), mgp = c(2,1,0))
  } 
  # Loop through list of Q matrices
  for(i in 1:length(kList)){
    # If population names are present (first column of matrix), remove these prior to plotting
    if(popNamesPresent){
      kList[[i]] <- kList[[i]][,-1]
    }
    # Update graphing parameters to allow for extra space at the bottom of the graph, for lines/popNames
    if(parFlag==TRUE){
      if(i == length(kList)){
        # par(mar = c(4,1,1,0.75) + 0.1)
        par(mar = c(5.5,1,1,0.75) + 0.1)
      }
    }
    # Main plot call, and title call
    Xpos <- barplot(t(kList[[i]]), beside= F, col=kColors, border = 1, space = 0.05, 
                    xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
    # For all but the last plot call, show tick marks (if specified)
      if(!is.null(tickMarks)){
        axis(1, at=tickMarks, labels = FALSE, lwd.ticks = 2.8, tck=-0.15)
        axis(1, at=tickMarks, labels = FALSE, lwd.ticks = 2.8, tck=1.05)
      }
  }
  return(Xpos)
}

# Wrapper for plot_multipleK, which just calls that function after reading in the CLUMPP files
Plot.AllK <- function(clumppPath, Ks, Colors, sampleNames, popNames, 
                          parFlag=TRUE, tickMarks=NULL, popNamesPresent=FALSE, majorClust=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Declare a list to be populated with filepaths to relevant CLUMPP files
  clumppList <- list()
  
  # For each K value, read in the corresponding CLUMPP files
  for(i in 1:length(Ks)){
    # Construct appropriate filepath and read in CLUMPP file
    Kfilepath <- paste0(clumppPath, "K", Ks[[i]], clumppFolder, "ClumppIndFile.output")
    Kclumpp <- read.CLUMPP(Kfilepath, sampleNames = sampleNames, popNames = popNames)
    # Add present CLUMPP file to list. Index is reduced by 1 because K values begin at K=2
    clumppList[[i]] <- Kclumpp
  }
  # Plot specified K values
  Xpos <- plot.multipleK(kList = clumppList, kValues = Ks, kColors = Colors, tickMarks=tickMarks, 
                         parFlag=parFlag, popNamesPresent = popNamesPresent)
  return(Xpos)
}

# %%%% VARIABLES %%%% ----
# Colors for different clusters
QUTA_colors <- brewer.pal(12, "Paired")
QUTA_colors <- QUTA_colors[c(1,2,4,3,5:12)]
# Variable file path: directory containing all CLUMPP outputs to read in
QUTA_clust2_clumppDir <- 
  "/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust2_seOnly/AllLoci/Output/CLUMPAK/Output/mainPipeline/"
# Read in text file of sample names
QUTA_clust2_sampleNames <- 
  as.list(read.table("/RAID1/QUTA_TX_RedOaks/Clustering/STRUCTURE/Clust2_seOnly/Clust2_sampleNames.txt", 
                     stringsAsFactors = FALSE))
# Reformat sample names as a vector
QUTA_clust2_sampleNames <- unname(unlist(QUTA_clust2_sampleNames))
# Remove prefixes ('SYST-MOR-000','OAK-M**-000' ), to make names discernible
QUTA_clust2_sampleNames <- sub('SYST-MOR-000','', QUTA_clust2_sampleNames)
QUTA_clust2_sampleNames <- sub('OAK-MOR-00','', QUTA_clust2_sampleNames)
QUTA_clust2_sampleNames <- sub('OAK-MOR-000','', QUTA_clust2_sampleNames)
QUTA_clust2_sampleNames <- sub('OAK-UMN-000','', QUTA_clust2_sampleNames)
# Group labels for Clust2
Clust2_labels <- c('"gravesii"','"grav._Langtrys"','"grav._admixed"','"grav. x emoryi"',
                   '"emoryi"','"canbyi"','"hypo."','"grav. x hypo."')
# Label and tick mark positions (Multiple K values)
Clust2_labelPositions_multipleK <- c(9, 24, 49, 82, 106, 123, 137, 155)
Clust2_tickMarks_multipleK <- c(0,19,26.4,66,91.3,116.4,127,146,164)

# %%%% PLOTTING %%%% ----
# %%%% ALL K VALUES ----
# Plot results from all K values
Xpos <- Plot.AllK(QUTA_clust2_clumppDir, Ks=2:7, QUTA_colors, sampleNames = QUTA_clust2_sampleNames, 
                  majorClust = TRUE, tickMarks = Clust2_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=Clust2_labelPositions_multipleK, y=-0.06, srt=35, adj=1, xpd=TRUE, labels=Clust2_labels, cex=1.2)

# %%%% SUBSET K VALUES ----
# Plot K values 2 through 4
Xpos <- Plot.AllK(QUTA_clust2_clumppDir, Ks=2:4, QUTA_colors, sampleNames = QUTA_clust2_sampleNames, 
                  majorClust = TRUE, tickMarks=Clust2_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=Clust2_labelPositions_multipleK, y=-0.06, srt=35, adj=1, xpd=TRUE, labels=Clust2_labels, cex=1.2)

# Plot K values 5 through 7
Xpos <- Plot.AllK(QUTA_clust2_clumppDir, Ks=5:7, QUTA_colors, sampleNames = QUTA_clust2_sampleNames, 
              majorClust = TRUE, tickMarks=Clust2_tickMarks_multipleK, popNamesPresent = FALSE)
# Add group labels
text(x=Clust2_labelPositions_multipleK, y=-0.06, srt=35, adj=1, xpd=TRUE, labels=Clust2_labels, cex=1.2)

# %%%% K=5 VALUES ----
# Specify graphing parameters to plot single K value
dev.off()
par(mar = c(8,1,0.5,3) + 0.1, oma = c(0,0.2,0,0), mgp = c(1,1,0))
# Label and tick mark positions (K=4)
Clust2_labelPositions_K5 <- c(14, 28, 57, 91, 117, 142, 160, 180)
Clust2_tickMarks_K5 <- c(0,21.6,30.2,75.8,99.6,133.5,145.4,167)

# Plot K = 5 on its own, returning x positions of vertical bars
Xpos <- Plot.K(QUTA_clust2_clumppDir, 5, QUTA_colors, mainTitle = "",  majorClust=TRUE, 
               popNamesPresent=FALSE, sampleNames = QUTA_clust2_sampleNames, showSampleNames = TRUE)
# Add title
title('QUTA_TxRedOaks: K=5', line = -1.3)
mtext('Single Reads Only; R98, 18,234 loci; Second STRUCTURE Run', line=-2.6)
# Plot tick marks (along bottom)
axis(1, at=Clust2_tickMarks_K5, labels = FALSE, lwd.ticks = 3, tck=-0.05)
axis(1, at=Clust2_tickMarks_K5, labels = FALSE, lwd.ticks = 3, tck=0.79)
# Add group labels
text(x=Clust2_labelPositions_K5, y=-0.03, srt=35, adj=1, xpd=TRUE, labels=Clust2_labels, cex=1.2)

# %%%% K=5 VALUES, WITH SAMPLE NAMES ----
# Specify graphing parameters to plot single K value
par(mar = c(8,1,0.5,3) + 0.1, oma = c(0,0.2,0,0), mgp = c(1,1,0))
# Plot K = 5 on its own, returning x positions of vertical bars
Xpos <- Plot.K(QUTA_clust2_clumppDir, 5, QUTA_colors, mainTitle = "",  majorClust=TRUE, 
               popNamesPresent=FALSE, sampleNames = QUTA_clust2_sampleNames, showSampleNames = TRUE)
# Add title
title('QUTA_TxRedOaks: K=5', line = -1.3)
mtext('Single Reads Only; R98, 18,234 loci; Second STRUCTURE Run', line=-2.6)
# Plot tick marks (along bottom)
axis(1, at=Clust2_tickMarks_K5, labels = FALSE, lwd.ticks = 3, tck=-0.05)
axis(1, at=Clust2_tickMarks_K5, labels = FALSE, lwd.ticks = 3, tck=0.79)
# Add sample names below the graph
text(x=Xpos, y=-0.007, srt=83, adj=1, xpd=TRUE, labels=QUTA_clust2_sampleNames, cex=0.75)
