#!/bin/bash

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %%% QUTA: STACKS PROCESS_RADTAGS SCRIPT %%%
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# This script calls the Stacks (v2.59) process_radtags command, which takes the QUTA Texas Red Oak raw paired-end data (from Fluoragenex) and performs the following steps:

# 1. Demultiplexing. This is done using the barcode text files found in the Demux/Barcodes directory. These barcodes were determined from spreadsheets generated by Fluoragenex,
#    which Austin Koontz obtained from Marlene Hahn. As part of the demultiplexing step, samples are renamed according to the sample names specified in the barcode text files.
#    Each barcode file is name according to the plate names.
# 2. Checking for barcodes. The argument --inline-null indicates that the barcode is included "inline" with the sequence on Read 1, and isn't found on read 2
#    ("null"). This was tested by taking the barcodes for different samples and searching for them  within the different plate files
#    (e.g. zcat UO_C1322_2.fastq.gz | grep TCCGGAGCGCTGCAG -A 2 -B 2). This illustrated the barcodes present at the beginning of each read (not in the
#    FASTQ header) in both the forward reads. For the reverse reads, we counted the number of instances a barcode was found in both forward and reverse reads (using a command like
#    (zcat UO_C1322_2.fastq.gz | grep TCCGGAGCGCTGCAG | wc -l). This demonstrated that barcodes were present at much higher orders of magnitude in forward than reverse reads
#    (for instance, in the example above, 3,163,140 counts in the forward read and 8,031 counts in the reverse read).
# 3. Checking for remnant restriction enzyme cutsites. The restriction enzyme PstI was used to digest this data; therefore, if the cutsite sequence for this enzyme (TGCAG)
#    is found in one of the reads, that read will be flagged. NOTE: the original barcodes provided to Austin from Marlene had the PstI RE cutsite sequence (TGCAG) appeneded to the
#    ends of all barcodes (for all plates). This sequence had to be removed manually from the barcodes prior to passing onto the Stacks software. Two samples on each plate (position 28
#    and position 73) had this same cutsite sequence within the barcode sequence used for those wells--but this isn't an issue, since barcodes are removed from samples prior to
#    remnant RE cutsites being trimmed (this step).
# 4. QC based on Illumina quality scores. The -c parameter removes any read with an uncalled base, and the -q parameter discards reads with low quality scores (based on a sliding
#    window of size 0.15*total read length; reads with an average score below 90% in this sliding widow are discarded). The -D parameter stores discarded reads in a file.
# 5. Merging paired-end reads into single output files

# The process_radtags command has to be called separately for each plate (to specify different barcode files). More information on the parameters in the command below can be found on the Stacks website.
# In addition to processing 3 plates of paired-end data, an additional plate of single-end data is provided. This plate of samples was demultiplexed prior being provided, and so no barcodes file
# is specified for this plate.
# This is the first step in the Genotyping workflow for this project. After demultiplexing and QC, samples are aligned to the the reference genome (Quercus rubra), and genotypes are called using the
# Stacks ref_map.pl script.

# Variabilize the filepath to the QUTA_TX_RedOaks raw data directory
QUTA_RawData=/RAID1/QUTA_TX_RedOaks/RawData
# Variabilize the filepath to the QUTA_TX_RedOaks demultiplexing directory
QUTA_Demux=/RAID1/QUTA_TX_RedOaks/Genotyping/Demux_QC

# %%% CALL PROCESS_RADTAGS COMMANDS %%%
# Plate C1322
process_radtags -1 $QUTA_RawData/C1322/UO_C1322_1.fastq.gz -2 $QUTA_RawData/C1322/UO_C1322_2.fastq.gz -b $QUTA_Demux/Barcodes/C1322_Barcodes.txt \
-o $QUTA_Demux/Output/C1322 --inline-null -e pstI --threads 24 -c -q -r

# Plate C1343
process_radtags -1 $QUTA_RawData/C1343/UO_C1343_1.fastq.gz -2 $QUTA_RawData/C1343/UO_C1343_2.fastq.gz -b $QUTA_Demux/Barcodes/C1343_Barcodes.txt \
-o $QUTA_Demux/Output/C1343 --inline-null -e pstI --threads 24 -c -q -r

# Plate C1440
process_radtags -1 $QUTA_RawData/C1440/UO_C1440_1.fastq.gz -2 $QUTA_RawData/C1440/UO_C1440_2.fastq.gz -b $QUTA_Demux/Barcodes/C1440_Barcodes.txt \
-o $QUTA_Demux/Output/C1440 --inline-null -e pstI --threads 24 -c -q -r

# Single end samples (In the /data/Quercus folder on the Hipp Lab Server, Sassy; not included in the Floragenex run which processed the 3 plates above)
# These samples have already been demultiplexed and have had barcodes removed, and so a barcodes file is not specified.
process_radtags -p $QUTA_RawData/SingleEndPlate -o $QUTA_Demux/Output/SingleEndPlate -e pstI --threads 24 -c -q -r

